In [101]:
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
from sklearn import preprocessing,svm,metrics
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [144]:
train = pd.read_csv('Copy of training_data.csv')
test = pd.read_csv('Copy of test_data.csv')

In [145]:
train = pd.read_csv('normalizedtraining.csv')


In [146]:
train.head()

patient_id  Chloride  SGPT  Sodium  T4  WBC  female  male  parameter_value  \
0           0         0     0       0   0    1       0     1           579.00   
1           1         0     0       0   1    0       0     1             5.00   
2           2         0     0       0   0    1       0     1             6.81   
3           3         0     0       0   1    0       0     1             5.70   
4           4         0     0       0   0    1       0     1             4.64   

   normalizedpara  normal  highproblem  lowproblem age_group  
0        0.038235       0            1           0       old  
1        0.004471       1            0           0       old  
2        0.004577       1            0           0     adult  
3        0.004512       1            0           0     adult  
4        0.004449       1            0           0     adult

In [147]:
min_max_scaler = preprocessing.MinMaxScaler()

In [148]:
train.parameter_value

0       579.00
1         5.00
2         6.81
3         5.70
4         4.64
         ...  
9995      9.14
9996      4.90
9997      9.80
9998      4.93
9999      6.00
Name: parameter_value, Length: 10000, dtype: float64

In [149]:
train.drop("parameter_value", axis =1, inplace = True)


In [150]:
train.head()

patient_id  Chloride  SGPT  Sodium  T4  WBC  female  male  normalizedpara  \
0           0         0     0       0   0    1       0     1        0.038235   
1           1         0     0       0   1    0       0     1        0.004471   
2           2         0     0       0   0    1       0     1        0.004577   
3           3         0     0       0   1    0       0     1        0.004512   
4           4         0     0       0   0    1       0     1        0.004449   

   normal  highproblem  lowproblem age_group  
0       0            1           0       old  
1       1            0           0       old  
2       1            0           0     adult  
3       1            0           0     adult  
4       1            0           0     adult

In [151]:
test.head()

patient_id  Chloride  SGPT  Sodium  T4  WBC  female  male  parameter_value  \
0           0         0     0       0   0    1       0     1             8.10   
1           1         0     0       0   1    0       0     1            13.00   
2           2         0     0       0   1    0       0     1             7.10   
3           3         0     0       0   0    1       0     1             5.62   
4           4         0     0       0   0    1       0     1          9350.00   

   normal  highproblem  lowproblem age_group  
0       1            0           0     adult  
1       0            1           0     adult  
2       1            0           0     adult  
3       1            0           0     adult  
4       1            0           0       old

In [152]:
train.drop("patient_id", axis =1, inplace = True)
#train.drop("male", axis =1, inplace = True)
#train.drop("female", axis =1, inplace = True)
test.drop("patient_id", axis =1, inplace = True)
#test.drop("male", axis =1, inplace = True)
#test.drop("female", axis =1, inplace = True)

In [153]:
train.head()

Chloride  SGPT  Sodium  T4  WBC  female  male  normalizedpara  normal  \
0         0     0       0   0    1       0     1        0.038235       0   
1         0     0       0   1    0       0     1        0.004471       1   
2         0     0       0   0    1       0     1        0.004577       1   
3         0     0       0   1    0       0     1        0.004512       1   
4         0     0       0   0    1       0     1        0.004449       1   

   highproblem  lowproblem age_group  
0            1           0       old  
1            0           0       old  
2            0           0     adult  
3            0           0     adult  
4            0           0     adult

In [107]:
#test.drop("patient_id", axis =1, inplace = True)


In [108]:
test.head()

Chloride  SGPT  Sodium  T4  WBC  female  male  parameter_value  normal  \
0         0     0       0   0    1       0     1             8.10       1   
1         0     0       0   1    0       0     1            13.00       0   
2         0     0       0   1    0       0     1             7.10       1   
3         0     0       0   0    1       0     1             5.62       1   
4         0     0       0   0    1       0     1          9350.00       1   

   highproblem  lowproblem age_group  
0            0           0     adult  
1            1           0     adult  
2            0           0     adult  
3            0           0     adult  
4            0           0       old

In [154]:
xtrain=train.iloc[:,:-1]
ytrain=train.iloc[:,[11]]
xtest=test.iloc[:,:-1]
ytest=test.iloc[:,[11]]

In [155]:
train_stats = train.describe()
#sns.pairplot(train_stats[train_stats.columns], diag_kind = "kde")

In [156]:
train_stats

Chloride          SGPT        Sodium            T4           WBC  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       0.119600      0.117200      0.126900      0.279600      0.356700   
std        0.324509      0.321675      0.332878      0.448825      0.479049   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      1.000000      1.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

             female          male  normalizedpara        normal   highproblem  \
count  10000.000000  10000.000000    10000.000000  10000.000000  10000.000000   
mean       0.115800      0.884200        0.025170      0.873300      0.057200   
std        0.320001      0.320001        0.546435      0.332653      0.232236   
min        0.000000      0.000000        0.000000      0.000000      0.000000   
25%        0.000000      1.000000        0.004571      1.000000      0.000000   
50%        0.000000      1.000000        0.004696      1.000000      0.000000   
75%        0.000000      1.000000        0.010118      1.000000      0.000000   
max        1.000000      1.000000       54.121824      1.000000      1.000000   

         lowproblem  
count  10000.000000  
mean       0.045000  
std        0.207314  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000

In [78]:
ytrain.head()

age_group
0       old
1       old
2     adult
3     adult
4     adult

In [140]:
scaler=preprocessing.StandardScaler()
scaler.fit(xtrain)
scaler.fit(xtest)


StandardScaler()

In [141]:
xtrain=scaler.transform(xtrain)
xtrain

array([[-0.37467437, -0.41131546, -0.37969035, ...,  0.41214596,
        -0.27937588, -0.2088623 ],
       [-0.37467437, -0.41131546, -0.37969035, ...,  0.41214596,
        -0.27937588, -0.2088623 ],
       [-0.37467437, -0.41131546, -0.37969035, ...,  0.41214596,
        -0.27937588, -0.2088623 ],
       ...,
       [-0.37467437, -0.41131546, -0.37969035, ...,  0.41214596,
        -0.27937588, -0.2088623 ],
       [-0.37467437, -0.41131546, -0.37969035, ..., -2.42632486,
        -0.27937588,  4.78784346],
       [-0.37467437, -0.41131546,  2.63372511, ...,  0.41214596,
        -0.27937588, -0.2088623 ]])

In [86]:
xtest=scaler.transform(xtest)
xtest

array([[-0.37467437, -0.41131546, -0.37969035, ...,  0.41214596,
        -0.27937588, -0.2088623 ],
       [-0.37467437, -0.41131546, -0.37969035, ..., -2.42632486,
         3.57940703, -0.2088623 ],
       [-0.37467437, -0.41131546, -0.37969035, ...,  0.41214596,
        -0.27937588, -0.2088623 ],
       ...,
       [ 2.66898424, -0.41131546, -0.37969035, ...,  0.41214596,
        -0.27937588, -0.2088623 ],
       [-0.37467437, -0.41131546, -0.37969035, ...,  0.41214596,
        -0.27937588, -0.2088623 ],
       [-0.37467437,  2.43122398, -0.37969035, ...,  0.41214596,
        -0.27937588, -0.2088623 ]])

In [158]:
clf=svm.SVC()
clf.fit(xtrain,ytrain)
acc=clf.score(xtest,ytest)
print(acc)
train_preds=clf.predict(xtrain)
test_preds=clf.predict(xtest)
print("cost of training model\n",metrics.confusion_matrix(ytrain,train_preds))
print("cost of training model\n",metrics.classification_report(ytrain,train_preds))
print("cost of testing model\n",metrics.confusion_matrix(ytest,test_preds))
print("cost of training model\n",metrics.classification_report(ytrain,train_preds))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


0.7547
cost of training model
 [[7746    0   49    0]
 [  91    0    2    0]
 [1945    0   72    0]
 [  95    0    0    0]]
cost of training model
               precision    recall  f1-score   support

       adult       0.78      0.99      0.88      7795
       child       0.00      0.00      0.00        93
         old       0.59      0.04      0.07      2017
        teen       0.00      0.00      0.00        95

    accuracy                           0.78     10000
   macro avg       0.34      0.26      0.24     10000
weighted avg       0.73      0.78      0.70     10000

cost of testing model
 [[7547    0    1    0]
 [  83    0    0    0]
 [2293    0    0    0]
 [  76    0    0    0]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


cost of training model
               precision    recall  f1-score   support

       adult       0.78      0.99      0.88      7795
       child       0.00      0.00      0.00        93
         old       0.59      0.04      0.07      2017
        teen       0.00      0.00      0.00        95

    accuracy                           0.78     10000
   macro avg       0.34      0.26      0.24     10000
weighted avg       0.73      0.78      0.70     10000



In [159]:
clf=RandomForestClassifier()
clf.fit(xtrain,ytrain)
acc=clf.score(xtest,ytest)
print(acc)
train_preds=clf.predict(xtrain)
test_preds=clf.predict(xtest)
print("cost of training model\n",metrics.confusion_matrix(ytrain,train_preds))
print("cost of training model\n",metrics.classification_report(ytrain,train_preds))
print("cost of testing model\n",metrics.confusion_matrix(ytest,test_preds))
print("cost of training model\n",metrics.classification_report(ytrain,train_preds))

<ipython-input-159-0f75b79490fb>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(xtrain,ytrain)


0.7254
cost of training model
 [[7642    4  143    6]
 [  59   30    4    0]
 [1451    0  562    4]
 [  77    1    4   13]]
cost of training model
               precision    recall  f1-score   support

       adult       0.83      0.98      0.90      7795
       child       0.86      0.32      0.47        93
         old       0.79      0.28      0.41      2017
        teen       0.57      0.14      0.22        95

    accuracy                           0.82     10000
   macro avg       0.76      0.43      0.50     10000
weighted avg       0.82      0.82      0.79     10000

cost of testing model
 [[7208  200  140    0]
 [  79    2    2    0]
 [2191   58   44    0]
 [  72    4    0    0]]
cost of training model
               precision    recall  f1-score   support

       adult       0.83      0.98      0.90      7795
       child       0.86      0.32      0.47        93
         old       0.79      0.28      0.41      2017
        teen       0.57      0.14      0.22        95

    a

In [160]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [161]:
model.fit(xtrain, ytrain)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [162]:
model.score(xtest, ytest)


0.7415

In [66]:
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline